### ISSUE TITLE
Creating a new doc should navigate to viewing the doc

### ISSUE THREAD

**Issue by kdoran** [kdoran/lookout#26]
steps to reproduce: 
1. create a new document with id `test-new-doc`
2. hit save
3. you're redirected to the document list view

what would be better:
3.1. the URL changes from `db-name/new/editing` to the created doc, `db-name/test-new-doc`
3.2 then the user is viewing the newly created doc, instead of the all docs page

**Comment by Olamuhammed** [comment]
Done Kevin.
